"""Task taxonomy for the eval and training sets.

Each family is one question over a class of states. States are
generated by a frontier model from `state_brief`; reference
distributions come from the teachers (see refs.py). Families marked
`heldout=True` never appear in training; they test transfer.

Keep questions narrow and options exhaustive (every Choice has an
escape hatch where the state may not fit). Descriptions are what the
model sees, so they carry the meaning; keys are for code.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class Family:
    key: str
    kind: str  # noul | choice | score
    state_brief: str  # what a state looks like; used to prompt the generator
    instructions: str
    criteria: Any  # per kind: None/dict for noul, dict for choice, list for score
    state_format: str = "text"  # text | json
    heldout: bool = False
    tags: tuple[str, ...] = field(default_factory=tuple)

    def question(self) -> dict[str, Any]:
        q: dict[str, Any] = {"type": self.kind, "instructions": self.instructions}
        if self.criteria is not None:
            q["criteria"] = self.criteria
        return q


FAMILIES: list[Family] = [
    # --- routing ---------------------------------------------------------
    Family(
        key="support_department",
        kind="choice",
        state_brief="a customer support message to a SaaS company (1-4 sentences), varied in tone, topic and clarity; some ambiguous, some multi-issue",
        instructions="Which team should handle this message?",
        criteria={
            "billing": "Charges, invoices, refunds, payment methods, subscription changes",
            "technical": "Bugs, errors, outages, integrations, API, performance",
            "account": "Login, password, permissions, user management, data export",
            "sales": "Pricing questions, upgrades, quotes, enterprise, trials",
            "other": "None of these teams fits, or it is not a support request",
        },
    ),
    Family(
        key="agent_next_action",
        kind="choice",
        state_brief="a JSON object with `conversation` (list of {role, text} between a customer and an assistant, 2-6 turns) and `pending_proposal` (what the assistant last offered, or null)",
        instructions=(
            "It is the assistant's turn. `pending_proposal` is something the assistant already offered in an earlier turn "
            "and has not yet been accepted or declined (null if nothing is pending). What should the assistant do now?"
        ),
        criteria={
            "answer": "Write a new reply: give information, ask a clarifying question, or restate/adjust the offer. No account action is taken",
            "action": "Take the account action now (refund, credit, plan change, add-on, cancellation): the customer has accepted the pending proposal, or policy clearly allows it",
            "escalate": "Hand off to a human agent because the assistant cannot or should not resolve this",
            "close": "The customer's need is fully resolved and they have indicated they are done; end the conversation",
            "wait": "Do nothing this turn: the assistant's last message already asked or offered something and the customer has not responded to it yet",
        },
        state_format="json",
    ),
    Family(
        key="email_folder",
        kind="choice",
        state_brief="an email with subject and body (business or personal), including newsletters, receipts, meeting requests, phishing attempts, personal notes",
        instructions="Which folder does this email belong in?",
        criteria={
            "action_required": "The recipient must do something (reply, approve, pay, attend)",
            "fyi": "Informational, no action needed",
            "receipt": "Purchase confirmation, invoice, shipping notice",
            "newsletter": "Bulk marketing or newsletter content",
            "suspicious": "Phishing, scam, or impersonation",
        },
    ),
    # --- sentiment / tone -------------------------------------------------
    Family(
        key="review_positive",
        kind="noul",
        state_brief="a short product or service review (1-3 sentences), spanning clearly positive, clearly negative, mixed, and sarcastic",
        instructions="Is this review positive overall?",
        criteria={"true": "The reviewer is satisfied and would recommend", "false": "The reviewer is dissatisfied or would not recommend"},
    ),
    Family(
        key="frustration_level",
        kind="score",
        state_brief="a message from a customer to a company (1-3 sentences), ranging from calm to furious, including passive-aggressive and resigned tones",
        instructions="How frustrated is the customer?",
        criteria=["Calm: neutral or friendly, no complaint energy", "Annoyed: mild irritation, still polite", "Frustrated: clearly upset, demanding a fix", "Angry: hostile, threatening to leave or escalate"],
    ),
    # --- urgency / priority -------------------------------------------------
    Family(
        key="ticket_urgency",
        kind="score",
        state_brief="a JSON object with `title`, `body`, `customer_tier` (free|pro|enterprise) and `affected_users` (integer) describing an issue report",
        instructions="How urgent is this ticket?",
        criteria=["Low: cosmetic or a question; can wait a week", "Medium: a workaround exists; this week", "High: blocks important work for some users; today", "Critical: outage, data loss, or security; now"],
        state_format="json",
    ),
    Family(
        key="message_urgent",
        kind="noul",
        state_brief="a short message (chat, email, or SMS) that may or may not be time-sensitive; vary explicit deadlines, implied urgency, and false urgency (marketing)",
        instructions="Does this message require action within the next few hours?",
        criteria={"true": "Delay of a few hours would cause real harm or a missed commitment", "false": "It can wait until tomorrow or later without consequence"},
    ),
    # --- policy / safety checks -------------------------------------------------
    Family(
        key="pii_present",
        kind="noul",
        state_brief="a snippet of text (log line, form submission, chat message, or note) that may contain personal data such as full names with addresses, phone numbers, emails, SSNs, card numbers; include tricky negatives like order IDs and public company info",
        instructions="Does this text contain personally identifiable information about a private individual?",
        criteria={"true": "Contains PII (email, phone, home address, government ID, card number, or a name combined with such details)", "false": "No PII, or only public/business information"},
    ),
    Family(
        key="content_policy",
        kind="choice",
        state_brief="a user-generated post on a community forum, ranging from ordinary to rule-breaking (harassment, spam, self-promotion, off-topic), with borderline cases",
        instructions="Which moderation outcome applies to this post?",
        criteria={
            "allow": "Ordinary post within the rules",
            "remove_spam": "Unsolicited promotion, link farming, or repetitive content",
            "remove_harassment": "Insults, threats, or targeting of a person or group",
            "off_topic": "On-rules but belongs in a different forum",
            "needs_human": "Genuinely ambiguous; a moderator should decide",
        },
    ),
    Family(
        key="refund_eligible",
        kind="noul",
        state_brief="a JSON object with `policy` (2-3 sentence refund policy), `purchase_date`, `request_date`, `reason` (customer's stated reason), `item_condition` (string)",
        instructions="Under `policy`, is this refund request eligible?",
        criteria={"true": "Every condition in the policy is met", "false": "At least one condition is not met, or the policy excludes this reason"},
        state_format="json",
    ),
    # --- extraction as choice -------------------------------------------------
    Family(
        key="pick_total",
        kind="choice",
        state_brief="a JSON object with `document` (a short invoice or receipt text with several money amounts: subtotal, tax, shipping, total, a previous balance, a discount) and `candidates` (list of the money strings found in it, in document order, 3-6 items)",
        instructions="Which entry in `candidates` is the amount the customer is being asked to pay now?",
        criteria={f"c{i}": f"candidates[{i}]" for i in range(6)} | {"none": "None of the candidates is the amount due"},
        state_format="json",
    ),
    Family(
        key="pick_meeting_time",
        kind="choice",
        state_brief="a JSON object with `thread` (2-4 short messages negotiating a meeting time; the final agreed time may be stated, implied, or unresolved) and `candidates` (list of 3-5 date/time strings mentioned in the thread)",
        instructions="Which entry in `candidates` is the meeting time the participants agreed on?",
        criteria={f"c{i}": f"candidates[{i}]" for i in range(5)} | {"none": "No time was agreed"},
        state_format="json",
    ),
    # --- code review -------------------------------------------------
    Family(
        key="code_has_bug",
        kind="noul",
        state_brief="a 5-20 line function in Python or JavaScript with a docstring saying what it should do; about half contain a real bug (off-by-one, wrong comparison, mutated default, unhandled None, wrong return), the rest are correct",
        instructions="Does this function have a bug that would make it violate its docstring on some valid input?",
        criteria={"true": "There is an input where the behavior contradicts the docstring", "false": "The function is correct for all valid inputs"},
    ),
    Family(
        key="pr_risk",
        kind="score",
        state_brief="a JSON object describing a pull request: `title`, `summary` (2-3 sentences), `files_changed` (list of paths), `lines_added`, `lines_removed`, `touches_migration` (bool), `has_tests` (bool)",
        instructions="How risky is merging this PR?",
        criteria=["Trivial: docs, comments, formatting", "Low: small, tested, isolated change", "Moderate: touches shared code or lacks tests", "High: schema/migration, auth, payments, or large untested change"],
        state_format="json",
    ),
    # --- language / semantics -------------------------------------------------
    Family(
        key="entailment",
        kind="choice",
        state_brief="a JSON object with `premise` (1-2 sentences) and `hypothesis` (1 sentence); balanced across entailment, contradiction, and neutral, with some subtle cases",
        instructions="Given `premise`, what is the status of `hypothesis`?",
        criteria={"entailed": "The hypothesis must be true if the premise is true", "contradicted": "The hypothesis must be false if the premise is true", "neutral": "The premise does not settle it"},
        state_format="json",
    ),
    Family(
        key="fact_or_opinion",
        kind="choice",
        state_brief="a single sentence that is a checkable factual claim, a personal opinion, a prediction, or a question",
        instructions="What kind of statement is this?",
        criteria={"fact_claim": "A claim about the world that could be checked", "opinion": "A preference, judgment, or feeling", "prediction": "A claim about the future", "question": "It asks rather than asserts"},
    ),
    Family(
        key="same_place",
        kind="noul",
        state_brief="a JSON object with `mention` (how a place is described in prose, e.g. 'the bakery on the canal called Bruno's') and `candidate` (a geocoder listing: name, address, category); half are the same real-world place, half are a same-named or nearby different place",
        instructions="Is `candidate` the same real-world place as `mention`?",
        criteria={"true": "Same establishment", "false": "A different place, even if the name matches"},
        state_format="json",
    ),
    # --- held-out families (transfer test; never in training) --------------------
    Family(
        key="expense_category",
        kind="choice",
        state_brief="a JSON object with `merchant`, `amount`, `memo` (may be empty), `date` describing a business expense",
        instructions="Which expense category does this belong to?",
        criteria={"travel": "Flights, hotels, taxis, mileage", "meals": "Restaurants, coffee, client dinners", "software": "Subscriptions, licenses, cloud", "equipment": "Hardware, furniture, supplies", "other": "Anything else"},
        state_format="json",
        heldout=True,
    ),
    Family(
        key="deadline_realistic",
        kind="score",
        state_brief="a JSON object with `task` (1-2 sentence description), `estimate_hours` (int), `deadline_days` (int), `team_size` (int), `dependencies` (list of strings, may be empty)",
        instructions="How realistic is meeting this deadline?",
        criteria=["Unrealistic: cannot be done in the time even with heroics", "Tight: possible only if nothing goes wrong", "Reasonable: normal effort with some slack", "Comfortable: plenty of slack"],
        state_format="json",
        heldout=True,
    ),
    Family(
        key="claim_supported",
        kind="noul",
        state_brief="a JSON object with `source` (a 2-4 sentence passage) and `claim` (1 sentence); half of the claims are supported by the source, half are not (contradicted, unmentioned, or overstated)",
        instructions="Is `claim` supported by `source`?",
        criteria={"true": "The source states or directly implies the claim", "false": "The source contradicts it, doesn't mention it, or the claim overstates it"},
        state_format="json",
        heldout=True,
    ),
    Family(
        key="log_severity",
        kind="choice",
        state_brief="a single application log line (with timestamp, level may be missing or wrong, message text) from a web service",
        instructions="What severity does this log line actually describe?",
        criteria={"debug": "Developer detail, no operational meaning", "info": "Normal operation", "warning": "Degraded but working; may need attention", "error": "An operation failed", "critical": "Service-wide failure or data loss"},
        heldout=True,
    ),
    Family(
        key="scheduling_conflict",
        kind="noul",
        state_brief="a JSON object with `existing` (list of 2-4 calendar events with start/end in ISO format and a timezone) and `proposed` (one event with start/end/timezone); half overlap, half don't, including timezone tricks and back-to-back edges",
        instructions="Does `proposed` overlap any event in `existing`?",
        criteria={"true": "Some time interval is shared", "false": "No overlap (back-to-back is not overlap)"},
        state_format="json",
        heldout=True,
    ),
]

BY_KEY = {f.key: f for f in FAMILIES}
TRAIN_FAMILIES = [f for f in FAMILIES if not f.heldout]
HELDOUT_FAMILIES = [f for f in FAMILIES if f.heldout]
